<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_shipment = $block->getShipment() ?>
<?php $_order = $block->getOrder() ?>
<?php if ($_shipment && $_order && $_shipment->getAllTracks()): ?>
<table class="shipment-track">
    <thead>
        <tr>
            <th><?= /* @escapeNotVerified */  __('Shipped By') ?></th>
            <th><?= /* @escapeNotVerified */  __('Tracking Number') ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($_shipment->getAllTracks() as $_item): ?>
        <tr>
            <td><?= $block->escapeHtml($_item->getTitle()) ?>:</td>
            <td><?= $block->escapeHtml($_item->getTitle()) == 'DHL' ? '<a href="https://nolp.dhl.de/nextt-online-public/set_identcodes.do?lang=de&idc=' . $block->escapeHtml($_item->getNumber()) . '" target="_blank">' . $block->escapeHtml($_item->getNumber()) . '</a>' : $block->escapeHtml($_item->getNumber()); ?></td>        </tr>
    <?php endforeach ?>
    </tbody>
</table>
<?php endif; ?>
