<div id="prescription-submission">
    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('prescription_submission_banner')->toHtml();?>
</div>

<div class="header-container">
	<div class="top-menu-container">
		<div class="container">
			<div class="row">
				<?php /* <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 top-bar">
					<?php echo $this->getChildHtml("store_switcher"); ?>
					<?php echo $this->getChildHtml("store_language"); ?>
					<?php echo $this->getChildHtml("currency"); ?>
					<?php echo $this->getChildHtml("social_header"); ?>
				</div> */ ?>
				<div class="col-md-9 col-sm-8 col-xs-12 col-md-offset-3 col-sm-offset-4">
                    <div class="row">
                        <div class="search-bar col-md-6 col-sm-8"><?php echo $this->getChildHtml("top.search"); ?></div>
                        <div class="service-icons col-md-6 col-sm-4">
                            <?php echo $this->getChildHtml("minicart");?>
                            <?php echo $this->getChildHtml("top_link"); ?>
                        </div>
                    </div>
				</div>
			</div>
		</div>
	</div>
	<div class="header">
		<div class="container">
			<div class="row">
				<div class="col-md-2 col-sm-3 col-xs-7 col-logo">
					<?php echo $this->getChildHtml("logo"); ?>
				</div>
				<div class="col-md-10 col-sm-9 col-xs-5 col-menu">
                    <?php /*echo $this->getChildHtml("minicart");*/?>
					<?php echo $this->getChildHtml("top.navigation.sections"); ?>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
    require(['jquery'],function($){
        $(document).ready(function($){
			$(window).scroll(function() {
				var num = $('.header-container').outerHeight();
				var screenWidth = $(window).width();
				
				if ($(this).scrollTop() > num && screenWidth >= 768 ){  
					$(".header").addClass("sticky");
				}
				else{
					$(".header").removeClass("sticky");
				}
			});
		});
    });
</script>
