<?php

use Magento\Framework\App\Action\Action;

if ($this->getConfig('enabled')) { // start enable module
    ?>
    <?php $_productCollection = $this->getProducts();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    ?>
    <div class="rokan-newproduct block">

        <?php
        if ($block->getMode() == 'grid') {
            $viewMode = 'grid';
            $image = 'category_page_grid';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        } else {
            $viewMode = 'list';
            $image = 'category_page_grid';
            $showDescription = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        }
        $pos = $block->getPositioned();

        ?>
        <?php if ($this->getConfig('title')) { ?>

            <div class="rokan-product-heading catwithimg-heading">
                <h2><?php echo $this->getConfig('title') ?></h2>
            </div>
        <?php } ?>
        <?php if (!$_productCollection->getSize()): ?>
            <div class="rokan-newproduct-slider">
                <p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
            </div>
        <?php else: ?>
        <?php
        $rows = 1;
        ?>
                <ul class="owl">
                    <?php $_collectionSize = $_productCollection->count() ?>
                    <?php $i = 0;
                    foreach ($_productCollection as $_product): ?>
                        <?php if ($i % $rows == 0) echo "<li class='item newproductslider-item'>"; ?>

                        <div class="product-item">
                            <?php if ($_product->getFinalPrice() < $_product->getPrice()): ?>
                                <span class="onsale">
											<span>Sale</span>
										</span>
                            <?php endif; ?>

                            <span class="newlabel">
                                    <span><?php echo __('New') ?></span>
                                </span>
                            <?php
                            $productImage = $block->getImage($_product, $image);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <?php // Product Image ?>
                            <div class="product-photo">
                                <a href="<?php /* @escapeNotVerified */
                                echo $_product->getProductUrl() ?>" class="product photo product-item-photo"
                                   tabindex="-1">
                                    <span class="image-switch">
                                        <?php echo $productImage->toHtml(); ?>
                                    </span>
                                </a>
                                <div class="addto-links-icons visible-onhover">
                                    <div class="action-inner">

                                        <?php if ($this->getConfig('addtowishlist') || $this->getConfig('addtocompare')) { ?>
                                            <ul class="add-to-links">
                                                <li>
                                                    <div class="quickview-product">
                                                        <a href="javascript:void(0)" data-role="quickview-button"
                                                           data-id="<?php echo $_product->getId(); ?>"
                                                           data-href="<?php echo $block->getUrl('quickview/product/quickview/id/' . $_product->getId()) ?>"
                                                           title="<?php echo $block->escapeHtml(__('Quick view')); ?>"
                                                           class="ajax diamond tooltip-hover" data-placement="top"
                                                           data-original-title="<?php echo('Quick view') ?>"><i
                                                                    class="fa fa-compress"></i></a>
                                                    </div>
                                                </li>

                                                <?php if ($this->getConfig('addtocompare')): ?>
                                                    <?php
                                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                    ?>
                                                    <li><a href="#"
                                                           class="action button tocompare"
                                                           title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                           aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                           data-post='<?php /* @escapeNotVerified */
                                                           echo $compareHelper->getPostDataParams($_product); ?>'
                                                           role="button">
                                                            <i class="fa fa-sliders"></i>
                                                        </a>
                                                    </li>
                                                <?php endif; ?>

                                                <?php if ($this->getConfig('addtowishlist')): ?>
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                        <li>
                                                            <a href="#"
                                                               class="action button towishlist"
                                                               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                               data-post='<?php /* @escapeNotVerified */
                                                               echo $block->getAddToWishlistParams($_product); ?>'
                                                               data-action="add-to-wishlist"
                                                               role="button">
                                                                <i class="fa fa-heart-o"></i>
                                                            </a>
                                                        </li>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </ul>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                            <div class="product-info">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <h3 class="product-name">
                                    <a href="<?php /* @escapeNotVerified */
                                    echo $_product->getProductUrl() ?>">
                                        <?php /* @escapeNotVerified */
                                        echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                    </a>
                                </h3>

                                <?php
                                $_attributeValue = $_product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_product);
                                if ($_attributeValue): ?>
                                    <div class="product-manufacturer">
                                        <?php echo $_attributeValue; ?>
                                    </div>
                                <?php endif; ?>

                                <?php if ($this->getConfig('show_price')): ?>
                                    <?php /* @escapeNotVerified */
                                    echo $block->getProductPrice($_product) ?>
                                <?php endif; ?>

                                <?php if ($this->getConfig('addtocart')) { ?>
                                    <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */
                                            echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product"
                                                       value="<?php /* @escapeNotVerified */
                                                       echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */
                                                echo Action::PARAM_NAME_URL_ENCODED; ?>"
                                                       value="<?php /* @escapeNotVerified */
                                                       echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="btn btn-add-to-cart">
                                                    <i class="icon icon_bag_alt"></i></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->getIsSalable()): ?>
                                                <div class="stock available"><span><?php /* @escapeNotVerified */
                                                        echo __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                        echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                <?php } ?>
                            </div>
                            <?php $i++; ?>
                        </div>
                        <?php if ($i % $rows == 0) echo "</li>"; ?>
                    <?php endforeach; ?>
                    <?php if ($i % $rows != 0) echo "</li>"; ?>
                </ul>
            </div>
        <?php endif; ?>
<?php } ?>