<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($crumbs && is_array($crumbs)) : ?>
<div class="breadcrumbs">
	<div class="container">
		<ul class="items">
			<?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
				<li class="item <?php /* @escapeNotVerified */ echo $crumbName ?>">
				<?php if ($crumbInfo['link']) : ?>
					<a href="<?php /* @escapeNotVerified */ echo $crumbInfo['link'] ?>" title="<?php echo $block->escapeHtml($crumbInfo['title']) ?>">
						<?php echo $block->escapeHtml($crumbInfo['label']) ?>
					</a>
				<?php elseif ($crumbInfo['last']) : ?>
					<strong><?php echo $block->escapeHtml($crumbInfo['label']) ?></strong>
				<?php else: ?>
					<?php echo $block->escapeHtml($crumbInfo['label']) ?>
				<?php endif; ?>
				</li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>


    <div class="cbp-row wh-page-title-bar">
        <div class="cbp-container">
            <div class="one whole wh-padding wh-page-title-wrapper">
                <h1 class="page-title">About</h1>
                <div class="cbp-row wh-breadcrumbs-bar">
                    <div class="cbp-container">
                        <div class="one whole wh-breadcrumbs-wrapper">
                            <div class="wh-breadcrumbs align-left">
                                <nav role="navigation" aria-label="Breadcrumbs" class="breadcrumb-trail breadcrumbs" itemprop="breadcrumb"><ul class="trail-items" itemscope="" itemtype="http://schema.org/BreadcrumbList"><meta name="numberOfItems" content="2"><meta name="itemListOrder" content="Ascending"><li itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem" class="trail-item trail-begin"><a href="http://senior.aislinthemes.com/modern" rel="home"><span itemprop="name">Home</span></a><meta itemprop="position" content="1"></li><li itemprop="itemListElement" itemscope="" itemtype="http://schema.org/ListItem" class="trail-item trail-end"><span itemprop="name">About</span><meta itemprop="position" content="2"></li></ul></nav>				</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
