<a href="https://www.idealo.de/preisvergleich/Shop/316774.html" target="_blank" class="tooltip-hover" data-placement="top" data-toggle="tooltip" data-original-title="BRANDvital ist gelisteter idealo-Partner">
    <img class="swap-on-hover__front-image" src="<?php echo $block->getViewFileUrl('images/idealo.png') ?>"
             alt="BRANDvital ist gelisteter idealo-Partner" />
</a>

<a href="https://www.shopvote.de/bewertung_brandvital_de_13619.html" target="_blank" class="tooltip-hover" data-placement="top" data-toggle="tooltip" data-original-title="Zertifiziert und kontrolliert durch Shopvote">
    <img class="swap-on-hover__front-image" src="<?php echo $block->getViewFileUrl('images/shopvote.png') ?>"
             alt="Zertifiziert und kontrolliert durch Shopvote" />
</a>
