<ul id="topnav" class="sf-menu">
    <li><a href="#">Lieferung verfolgen</a></li>
    <li><a href="#">Kundenservice</a></li>

	<?php if($this->helper('Benlau\Themeoption\Helper\Data')->isLoggedIn()): ?>
	<li><a href="<?php echo $this->helper('Benlau\Themeoption\Helper\Data')->getBaseUrl('customer/account/'); ?>" rel="nofollow"><?php echo __('Mein Konto') ?></a></li>
	<?php else: ?>
	<li><a href="<?php echo $this->helper('Benlau\Themeoption\Helper\Data')->getBaseUrl('customer/account/login/'); ?>" rel="nofollow"><?php echo __('Anmelden') ?></a></li>
	<?php endif ?>
</ul>