<?php 
use Magento\Framework\App\Action\Action;
if($this->getConfig('enabled')){ // start enable module

    $_productCollection = $this->getProducts();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
	?>
	<div class="rokan-onsaleproduct">
		
		<?php			
			if ($block->getMode() == 'grid') {
				$viewMode = 'grid';
				$image = 'category_page_grid';
				$showDescription = false;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			} else {
				$viewMode = 'list';
				$image = 'category_page_grid';
				$showDescription = true;
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			}
			$pos = $block->getPositioned();
			
		?>
		<?php if($this->getConfig('title')){?>
			<div class="rokan-product-heading rokan-onsale-heading"><h2><?php echo $this->getConfig('title')?></h2></div>
		<?php }?>
		<?php if(!$_productCollection->getSize()): ?> 
			<div class="rokan-onslate-slider">	
				<p class="note-msg"><?php echo __('There are no products matching the selection.') ?></p>
			</div>
		<?php else: ?>
			<?php
			$rows = 1;
			?>	
			<ul class="owl">
				<?php $_collectionSize = $_productCollection->count() ?>
				<?php $i=0; foreach ($_productCollection as $_product): ?>
					<?php if($i %$rows == 0) echo "<li class='item featuredproductslider-item'>"; ?>

						<div class="product-item">
							<?php
							$productImage = $block->getImage($_product, $image);
							if ($pos != null) {
								$position = ' style="left:' . $productImage->getWidth() . 'px;'
									. 'top:' . $productImage->getHeight() . 'px;"';
							}
							?>
							<div class="product-photo">
								<?php // Product Image ?>
								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
									<span class="image-switch">
										<?php echo $productImage->toHtml(); ?>
									</span>
								</a>
							</div>
							<div class="product-info">
								<?php
									$_productNameStripped = $block->stripTags($_product->getName(), null, true);
								?>
								<h3 class="product-name">
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
								</h3>
                                <?php
                                $_attributeValue =$_product->getResource()->getAttribute('manufacturer')->getFrontend()->getValue($_product);
                                if ($_attributeValue): ?>
                                <div class="product-manufacturer">
                                     <?php echo $_attributeValue; ?>
                                </div>
                                <?php endif; ?>

                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>

								<?php if( $this->getConfig('description')){?>
									<div class="ma-desc">
										 <?php echo $block->getProductDetailsHtml($_product); ?>
									</div>
								<?php }?>
							</div>
						<?php $i++;?>
					</div>
					<?php if($i %$rows == 0) echo "</li>"; ?>                  
				<?php endforeach; ?>
					<?php if($i %$rows != 0) echo "</li>"; ?>                
			</ul>
			<script>
				require([
					'jquery',
					'mage/mage',
					'rokanthemes/owl'
				], function ($) {
					'use strict';

					jQuery(".rokan-onsaleproduct .owl").owlCarousel({
						lazyLoad: true,
						autoPlay : false,
						items : 4,
						itemsDesktop : [1199,1],
						itemsDesktopSmall : [980,1],
						itemsTablet: [768,1],
						itemsMobile : [479,1],
						slideSpeed : 500,
						paginationSpeed : 500,
						rewindSpeed : 500,
						navigation : true,
						stopOnHover : true,
						pagination :false,
						scrollPerPage:true,
					});
				});
			</script>
	<?php endif; ?>
	</div>
<?php } ?>