<a href="#" target="_blank" class="tooltip-hover" data-placement="top" data-toggle="tooltip" data-original-title="BRANDvital ist gelisteter idealo-Partner">
    <figure class="swap-on-hover">
        <img class="swap-on-hover__front-image" src="<?php echo $block->getViewFileUrl('images/idealo_gray.png') ?>"
             alt="BRANDvital ist gelisteter idealo-Partner" />
        <img class="swap-on-hover__back-image" src="<?php echo $block->getViewFileUrl('images/idealo.png') ?>"
             alt="BRANDvital ist gelisteter idealo-Partner">
    </figure>
</a>

<a href="#" target="_blank" class="tooltip-hover" data-placement="top" data-toggle="tooltip" data-original-title="Zertifiziert und kontrolliert durch Shopvote">
    <figure class="swap-on-hover">
        <img class="swap-on-hover__front-image" src="<?php echo $block->getViewFileUrl('images/shopvote_gray.png') ?>"
             alt="Zertifiziert und kontrolliert durch Shopvote" />
        <img class="swap-on-hover__back-image" src="<?php echo $block->getViewFileUrl('images/shopvote.png') ?>"
             alt="Zertifiziert und kontrolliert durch Shopvote" />
    </figure>
</a>
