<ul class="top-link">
	<?php if($this->helper('Rokanthemes\Themeoption\Helper\Data')->isLoggedIn()): ?>
	<li><a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('customer/account/'); ?>"><span><?php echo __('Mein Konto') ?></span></a></li>
	<?php else: ?>
	<li><a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('customer/account/login/'); ?>"><span><?php echo __('Mein Konto') ?></span></a></li>
	<?php endif ?>
</ul>