<section id="slider">
    <div class="container">
        <h5 class="title">Slider</h5>
        <div class="row">
            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('hmv_home_slider')->toHtml(); ?>
        </div>
    </div>
</section>

<section id="slider-bottom">
    <div class="container">
        <div class="row">
            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('hmv_home_instructions')->toHtml(); ?>
        </div>
    </div>
</section>

<section id="bestsellers">
    <div class="container">
        <div class="row p-t-80 p-b-80">
            <div class="column inner">
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('hmv_home_bestsellers')->toHtml(); ?>
            </div>
            <div class="column inner">
                <div class="box">
                    <a href="/rollator" class="box-link"></a>
                    <img src="https://placeholder.pics/svg/300x350">
                    <h4>Rollator</h4>
                </div>
            </div>
            <div class="column inner">
                <div class="box">
                    <a href="/rollstuhl" class="box-link"></a>
                    <img src="https://placeholder.pics/svg/300x350">
                    <h4>Rollstuhl</h4>
                </div>
            </div>
            <div class="column inner">
                <div class="box">
                    <a href="/elektromobil" class="box-link"></a>
                    <img src="https://placeholder.pics/svg/300x350">
                    <h4>Elektromobil</h4>
                </div>
            </div>
        </div>
    </div>
</section>



<section id="services">
    <div class="container">
        <h5 class="title">Service</h5>
        <div class="row">
            <div class="column">1</div>
            <div class="column">2</div>
        </div>
    </div>
</section>