<div class="top-content-home">
    <div class="box-new">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-xs-9">
                    <?php echo $block->getLayout()->createBlock('Rokanthemes\Newproduct\Block\Newproduct')->setTemplate('Rokanthemes_Newproduct::newproduct.phtml')->toHtml(); ?>
                </div>
                <div class="col-md-3 col-xs-3 sidebar-container sidebar-new-products">
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sidebar_new_products')->toHtml(); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="section-welcome">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-xs-9">
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('section_welcome')->toHtml(); ?>
                </div>
                <div class="col-md-3 col-xs-3 sidebar-container sidebar-banner">
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sidebar_banner_home')->toHtml(); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="onsale-countdown">
        <div class="container">
            <div class="row">
                <div class="col-xl-9">
                    <?php echo $block->getLayout()->createBlock('Rokanthemes\PriceCountdown\Block\Pricecountdown')->setTemplate('Rokanthemes_PriceCountdown::pricecountdown.phtml')->toHtml(); ?>
                </div>
                <div class="col-xl-3 sidebar-container sidebar-countdown-products">
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sidebar_countdown_products')->toHtml(); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="group-product">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-xs-9">
                    <?php echo $block->getLayout()->createBlock('Magento\Catalog\Block\Product\ListProduct')->setTemplate('Magento_Catalog::product/category_bestseller.phtml')->setCategoryId(146)->toHtml(); ?>
                </div>
                <div class="col-md-3 col-xs-3 sidebar-container sidebar-bestseller-products">
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sidebar_besteller_products')->toHtml(); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="group-product">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-xs-9">
                    <?php echo $block->getLayout()->createBlock('Rokanthemes\Onsaleproduct\Block\Onsaleproduct')->setTemplate('Rokanthemes_Onsaleproduct::onsaleproduct.phtml')->toHtml(); ?>
                </div>
                <div class="col-md-3 col-xs-3 sidebar-container sidebar-onsale-products">
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sidebar_onsale_products')->toHtml(); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="section-seo">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-xs-9">
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('section_seo')->toHtml(); ?>
                </div>
                <div class="col-md-3 col-xs-3">
                    <div class="sidebar-container sidebar-seo">
                        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sidebar_seo')->toHtml(); ?>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="section-brands">
        <div class="container">
            <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('section_brands')->toHtml(); ?>
        </div>
    </div>
</div>